# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-874f879a-b016-41b2-94a2-2aae6eea3d5e";
      fsType = "ext4";
    };
  boot.initrd.luks.devices."luks-d71a2cca-357e-45ca-86ec-fe7bbf3fc932".device = "/dev/disk/by-uuid/d71a2cca-357e-45ca-86ec-fe7bbf3fc932";
  boot.initrd.luks.devices."luks-874f879a-b016-41b2-94a2-2aae6eea3d5e".device = "/dev/disk/by-uuid/874f879a-b016-41b2-94a2-2aae6eea3d5e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/B752-37B3";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d71a2cca-357e-45ca-86ec-fe7bbf3fc932"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
